import './globals.css'
import TopNavigator from "@/components/TopNavigator";
import SearchBar from "@/components/SearchBar";
import MenuSide from "@/components/MenuSide";

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
                                       children,
                                   }: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
        <body className={'bg-blue-400'}>
        <TopNavigator centerChildren={<SearchBar/>}/>
        <div className='flex mt-10 h-max'>
            <div className='flex-1'>
                <MenuSide items={[{
                    title: 'a',
                    icon: ''
                }]}/>
            </div>
            <div className='flex-1'></div>
            <div className='flex-1'></div>
        </div>
        {children}
        </body>
        </html>
    )
}
